package com.expensetracker.data.db
import com.expensetracker.domain.model.*
import com.expensetracker.service.SmsParser
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
private val FMT=DateTimeFormatter.ISO_LOCAL_DATE_TIME
fun now():String=LocalDateTime.now().format(FMT)
fun fmtDt(dt:LocalDateTime):String=dt.format(FMT)
fun parseDt(s:String):LocalDateTime=try{LocalDateTime.parse(s,FMT)}catch(_:Exception){LocalDateTime.now()}
fun safeCategory(s:String):ExpenseCategory=try{ExpenseCategory.valueOf(s)}catch(_:Exception){ExpenseCategory.OTHER}
fun normalizeMerchant(raw:String):String=raw.lowercase().replace(Regex("[^a-z0-9 ]"),"").replace(Regex("\\s+")," ").trim().take(40)
fun extractCardNumber(sms:String):String=Regex("""(?:card|a/c|ac|account)\s*(?:no\.?|number|ending|X+)?[\sX*]*(\d{4})\b""",RegexOption.IGNORE_CASE).find(sms)?.groupValues?.get(1)?:""
fun extractBankName(sender:String):String=listOf("QNB","CBQ","DOHA","MASRAF","HSBC","QIIB","DUKHAN","AHLIBANK","COMMERCIAL").firstOrNull{sender.uppercase().contains(it)}?:sender.take(20)
fun TransactionEntity.toDomain()=Transaction(id=id,uuid=uuid,amount=amount,currency=currency,merchant=merchant,normalizedMerchant=normalizedMerchant,category=safeCategory(category),subcategory=subcategory,transactionType=try{TransactionType.valueOf(transactionType)}catch(_:Exception){TransactionType.EXPENSE},paymentMethod=try{PaymentMethod.valueOf(paymentMethod)}catch(_:Exception){PaymentMethod.DEBIT_CARD},walletId=walletId,walletName=walletName,dateTime=parseDt(dateTime),bankName=bankName,accountLast4=accountLast4,accountLabel=accountLabel,balance=balance,rawSms=rawSms,isManual=isManual,isExcluded=isExcluded,isRecurring=isRecurring,recurringGroupId=recurringGroupId,isTransfer=isTransfer,isRefund=isRefund,note=note,tags=if(tags.isBlank())emptyList()else tags.split("|").filter{it.isNotBlank()},confidenceScore=confidenceScore,userEdited=userEdited,sender=sender,createdAt=parseDt(createdAt),updatedAt=parseDt(updatedAt))
fun Transaction.toEntity()=TransactionEntity(id=id,uuid=uuid,amount=amount,currency=currency,merchant=merchant,normalizedMerchant=normalizedMerchant,category=category.name,subcategory=subcategory,transactionType=transactionType.name,paymentMethod=paymentMethod.name,walletId=walletId,walletName=walletName,dateTime=fmtDt(dateTime),bankName=bankName,accountLast4=accountLast4,accountLabel=accountLabel,balance=balance,rawSms=rawSms,isManual=isManual,isExcluded=isExcluded,isRecurring=isRecurring,recurringGroupId=recurringGroupId,isTransfer=isTransfer,isRefund=isRefund,note=note,tags=tags.joinToString("|"),confidenceScore=confidenceScore,userEdited=userEdited,sender=sender,createdAt=fmtDt(createdAt),updatedAt=fmtDt(updatedAt))
fun SmsParser.ParsedTransaction.toEntity()=TransactionEntity(uuid=java.util.UUID.randomUUID().toString(),amount=amount,currency="QAR",merchant=merchant,normalizedMerchant=normalizeMerchant(merchant),category=category.name,transactionType=if(isRefund)"REFUND" else if(isTransfer)"TRANSFER" else "EXPENSE",paymentMethod="DEBIT_CARD",dateTime=fmtDt(dateTime),bankName=extractBankName(sender),accountLast4=extractCardNumber(rawSms),balance=balance,rawSms=rawSms,isManual=false,note="",tags="",confidenceScore=confidenceScore,sender=sender,smsHash=smsHash,createdAt=now(),updatedAt=now())
fun WalletEntity.toDomain()=Wallet(id=id,name=name,type=try{WalletType.valueOf(type)}catch(_:Exception){WalletType.BANK},currency=currency,balance=balance,color=color,emoji=emoji,isHidden=isHidden,isArchived=isArchived,bankName=bankName,accountLast4=accountLast4,createdAt=parseDt(createdAt))
fun Wallet.toEntity()=WalletEntity(id=id,name=name,type=type.name,currency=currency,balance=balance,color=color,emoji=emoji,isHidden=isHidden,isArchived=isArchived,bankName=bankName,accountLast4=accountLast4,createdAt=fmtDt(createdAt))
fun BudgetEntity.toDomain()=Budget(id=id,name=name,category=safeCategory(category),monthlyLimit=monthlyLimit,period=try{BudgetPeriod.valueOf(period)}catch(_:Exception){BudgetPeriod.MONTHLY},month=month,year=year,rollover=rollover,alertAt=alertAt)
fun Budget.toEntity()=BudgetEntity(id=id,name=name,category=category.name,monthlyLimit=monthlyLimit,period=period.name,month=month,year=year,rollover=rollover,alertAt=alertAt)
fun SavingsGoalEntity.toDomain()=SavingsGoal(id=id,name=name,targetAmount=targetAmount,currentAmount=currentAmount,emoji=emoji,color=color,deadline=deadline?.let{parseDt(it)},status=try{GoalStatus.valueOf(status)}catch(_:Exception){GoalStatus.ACTIVE},createdAt=parseDt(createdAt))
fun SavingsGoal.toEntity()=SavingsGoalEntity(id=id,name=name,targetAmount=targetAmount,currentAmount=currentAmount,emoji=emoji,color=color,deadline=deadline?.let{fmtDt(it)},status=status.name,createdAt=fmtDt(createdAt))
fun MerchantRuleEntity.toDomain()=MerchantRule(id=id,pattern=pattern,displayName=displayName,category=safeCategory(category),applyToFuture=applyToFuture,applyToPast=applyToPast,createdAt=parseDt(createdAt))
fun MerchantRule.toEntity()=MerchantRuleEntity(id=id,pattern=pattern,displayName=displayName,category=category.name,applyToFuture=applyToFuture,applyToPast=applyToPast,createdAt=fmtDt(createdAt))
