package com.expensetracker.service
import com.expensetracker.domain.model.ExpenseCategory
import java.security.MessageDigest
import java.time.LocalDateTime
object SmsParser {
    data class ParsedTransaction(val amount:Double,val merchant:String,val balance:Double?,val category:ExpenseCategory,val dateTime:LocalDateTime,val rawSms:String,val smsHash:String,val sender:String="",val confidenceScore:Float=0.8f,val isRefund:Boolean=false,val isTransfer:Boolean=false)
    data class ParserConfig(val currencySymbol:String="QAR",val trustedSenders:List<String>=emptyList(),val debitKeywords:List<String>=emptyList(),val creditKeywords:List<String>=emptyList())
    private val DD=listOf("debited","deducted","spent","paid","payment","purchase","withdrawn","charged","debit","pos ","txn","transaction","sent")
    private val DC=listOf("credited","received","credit","deposited","refund","cashback","salary")
    private val OTP=listOf("otp","one time","verification code","do not share","expires in")
    private val REF=listOf("refund","reversal","reversed","cashback")
    private val TRF=listOf("transfer","neft","imps","rtgs","sent to")
    private fun ap(c:String)=listOf(Regex("""(?:${Regex.escape(c)}|QAR|SAR|AED|KWD|BHD|OMR|Rs\.?|INR|USD|\$|EUR|GBP)\s*([0-9,]+(?:\.[0-9]{1,3})?)""",RegexOption.IGNORE_CASE),Regex("""([0-9,]+(?:\.[0-9]{1,3})?)\s*(?:${Regex.escape(c)}|QAR|SAR|AED|KWD)""",RegexOption.IGNORE_CASE),Regex("""(?:amount|amt)\s*(?:of|:)?\s*(?:[A-Z]{2,4})?\s*([0-9,]+(?:\.[0-9]{1,3})?)""",RegexOption.IGNORE_CASE),Regex("""(?:debited|paid|spent|charged)\s+(?:with\s+)?(?:[A-Z]{2,4}\s+)?([0-9,]+(?:\.[0-9]{1,3})?)""",RegexOption.IGNORE_CASE))
    private val BP=listOf(Regex("""(?:avl|avail|available|bal|balance)\s*(?:bal|balance)?\s*(?:is|:|-|=)?\s*(?:[A-Z]{2,4})?\s*([0-9,]+(?:\.[0-9]{1,3})?)""",RegexOption.IGNORE_CASE),Regex("""(?:[A-Z]{2,4})\s*([0-9,]+(?:\.[0-9]{1,3})?)\s*(?:available|avl|bal|balance)""",RegexOption.IGNORE_CASE))
    private val MP=listOf(Regex("""(?:at|to|merchant[:\s]+)\s+([A-Za-z0-9 \-&'.\/]+?)(?:\s+on\s+|\s+ref|\s+txn|\s*\.|,|\s{2,}|$)"""),Regex("""(?:purchase|payment|paid)\s+(?:at|to)\s+([A-Za-z0-9 \-&'.]+?)(?:\s+on|\.|,|$)""",RegexOption.IGNORE_CASE),Regex("""POS\s+([A-Za-z0-9 \-&'.]+?)(?:\s+\d|\.|,|$)"""),Regex("""(?:towards|for)\s+([A-Za-z0-9 \-&'.]+?)(?:\s+on|\s+ref|\.|,|$)""",RegexOption.IGNORE_CASE))
    val CATEGORY_KEYWORDS:Map<ExpenseCategory,List<String>>=mapOf(ExpenseCategory.FOOD to listOf("talabat","zomato","deliveroo","careem food","noon food","restaurant","cafe","coffee","pizza","burger","kfc","mcdonalds","subway","dining","biryani","shawarma","starbucks","tim hortons","hardees","popeyes","wendys","dominos","papa johns","shake shack","nandos"),ExpenseCategory.GROCERY to listOf("lulu","carrefour","safari","al meera","monoprix","spinneys","waitrose","family food","geant","hypermarket","supermarket","grocery","spar","grand mart","fresh mart"),ExpenseCategory.TRANSPORT to listOf("uber","careem","karwa","taxi","metro","mowasalat","bus","parking","salik","toll","lyft","bolt","indrive"),ExpenseCategory.FUEL to listOf("woqod","fuel","petrol","gas station","filling station","shell","total","q8","qatar fuel","caltex"),ExpenseCategory.SHOPPING to listOf("amazon","noon","namshi","ounass","zara","h&m","ikea","centrepoint","max fashion","splash","landmark","ace hardware","home centre","virgin megastore","plug","istore","apple store","sharaf dg"),ExpenseCategory.BILLS to listOf("ooredoo","vodafone qatar","kahramaa","electricity","water","utility","internet","broadband","telecom","stc","du ","etisalat","phone bill","postpaid","recharge"),ExpenseCategory.SUBSCRIPTION to listOf("netflix","spotify","apple","google play","microsoft","adobe","aws","shahid","osn","bein sport","disney","hotstar","amazon prime","youtube premium","icloud","dropbox","linkedin","zoom","slack","chatgpt"),ExpenseCategory.HEALTH to listOf("hospital","clinic","pharmacy","medical","doctor","dental","hamad","aster","american hospital","sidra","qmc","medicine","optician","lab","diagnostic"),ExpenseCategory.ENTERTAINMENT to listOf("cinema","movie","vox","reel","muvi","bowling","escape room","theme park","gaming","playstation","xbox","steam","concert","event","ticket"),ExpenseCategory.EDUCATION to listOf("school","university","tuition","course","education","training","books","stationery","qatar university","british council","udemy","coursera"),ExpenseCategory.TRAVEL to listOf("qatar airways","airline","flight","airport","hotel","booking","airbnb","holiday","travel","resort","marriott","hilton","hyatt","rotana","intercontinental","expedia","agoda"),ExpenseCategory.SALARY to listOf("salary","payroll","wage","income","monthly pay"),ExpenseCategory.TRANSFER to listOf("transfer","neft","imps","rtgs","sent to","wire"))
    fun getCategoryKeywords(cat:ExpenseCategory):List<String>=CATEGORY_KEYWORDS[cat]?:emptyList()
    fun categorize(merchant:String,sms:String=""):ExpenseCategory{val m=merchant.lowercase();for((cat,kws) in CATEGORY_KEYWORDS){if(kws.any{m.contains(it)})return cat};val s=sms.lowercase();for((cat,kws) in CATEGORY_KEYWORDS){if(kws.any{s.contains(it)})return cat};return ExpenseCategory.OTHER}
    fun isDebitTransaction(sms:String,config:ParserConfig=ParserConfig()):Boolean{val l=sms.lowercase();if(OTP.any{l.contains(it)})return false;val ad=DD+config.debitKeywords;val ac=DC+config.creditKeywords;val hd=ad.any{l.contains(it)};val hc=ac.any{l.contains(it)};if(hc&&!hd)return false;return hd&&ap(config.currencySymbol).any{it.containsMatchIn(sms)}}
    fun isTrustedSender(sender:String,config:ParserConfig):Boolean{if(config.trustedSenders.isEmpty())return true;return config.trustedSenders.any{sender.lowercase().contains(it.lowercase())}}
    fun parse(sms:String,sender:String="",receivedAt:LocalDateTime=LocalDateTime.now(),config:ParserConfig=ParserConfig()):ParsedTransaction?{if(!isDebitTransaction(sms,config))return null;val patterns=ap(config.currencySymbol);val amount=eAmt(sms,patterns)?:return null;val merchant=eMerch(sms).ifBlank{sender.ifBlank{"Unknown"}};val balance=eBal(sms);val l=sms.lowercase();val isRefund=REF.any{l.contains(it)};val isTransfer=TRF.any{l.contains(it)};val cat=categorize(merchant,sms);val conf=conf(sms,merchant,cat);return ParsedTransaction(amount,merchant,balance,cat,receivedAt,sms,hash(sms),sender,conf,isRefund,isTransfer)}
    private fun conf(sms:String,merchant:String,cat:ExpenseCategory):Float{var s=0.4f;if(ap("QAR").first().containsMatchIn(sms))s+=0.2f;if(merchant.length>3&&merchant!="Unknown")s+=0.2f;if(CATEGORY_KEYWORDS[cat]?.any{merchant.lowercase().contains(it)}==true)s+=0.2f;return s.coerceIn(0f,1f)}
    private fun eAmt(sms:String,patterns:List<Regex>):Double?{for(p in patterns){val v=p.find(sms)?.groupValues?.get(1)?.replace(",","")?.toDoubleOrNull();if(v!=null&&v>0&&v<10_000_000)return v};return null}
    private fun eMerch(sms:String):String{for(p in MP){val m=p.find(sms)?.groupValues?.get(1)?.trim()?:continue;if(m.length>=2)return m.replace(Regex("""\b\d{4,}\b"""),"").trim().take(50)};return ""}
    private fun eBal(sms:String):Double?{for(p in BP){val v=p.find(sms)?.groupValues?.get(1)?.replace(",","")?.toDoubleOrNull();if(v!=null)return v};return null}
    fun hash(sms:String):String=MessageDigest.getInstance("SHA-256").digest(sms.toByteArray()).joinToString(""){"%02x".format(it)}.take(16)
}
